# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         String-FormatX
version:      0.01
version_from: lib/String/FormatX.pm
installdirs:  site
requires:
    CGI::Carp:                     0
    Number::Format:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
